.github/workflows/IJ.yml
.github/workflows/ci.yml

Add GitHub actions

---

src/main/java/com/redhat/devtools/intellij/common/utils/ExecHelper.java

Signed-off-by: Rob Stryker <rob@oxbeef.net>

Fixes #4 - allow arbitrary process to connect to terminal

---

build.gradle
src/main/java/com/redhat/devtools/intellij/common/tree/StructureTreeModelFactory.java

Provide StructureTreeModel factory to overcome API compat issues IC 2019.3+ (#6)

---

.github/workflows/IJ.yml
src/test/java/com/redhat/devtools/intellij/common/utils/DownloadHelperTest.java

Add IntelliJ 2020.2

---

src/main/java/com/redhat/devtools/intellij/common/utils/ConfigHelper.java
src/main/java/com/redhat/devtools/intellij/common/utils/ConfigWatcher.java

ConfigWatcher: use provided path instead of default (#13)

---

src/main/java/com/redhat/devtools/intellij/common/utils/DateHelper.java
src/test/java/com/redhat/devtools/intellij/common/utils/DateHelperTest.java

this is linked to https://github.com/redhat-developer/intellij-tekton/issues/205

Avoid returning negative seconds value when start date is older than end

---

src/main/java/com/redhat/devtools/intellij/common/actions/TreeAction.java

fixes #19 & https://github.com/redhat-developer/intellij-kubernetes/issues/109

dont NPE in TreeAction#isVisible if element is null (#19)

---

src/main/java/com/redhat/devtools/intellij/common/utils/ConfigWatcher.java

log watcher service exception (was: printed to std error) (#17)

---

src/main/java/com/redhat/devtools/intellij/common/utils/ConfigHelper.java

Allow users to compare existing/new context & all contexts

---

.github/workflows/IJ.yml
build.gradle
gradle/wrapper/gradle-wrapper.properties
src/test/java/com/redhat/devtools/intellij/common/utils/DownloadHelperTest.java
src/test/java/com/redhat/devtools/intellij/common/utils/MessagesHelper.java

Add 2020.3

---

build.gradle
src/main/java/com/redhat/devtools/intellij/common/utils/ConfigHelper.java

use kubernetes-client 5.0.0 (#24)

---

src/main/java/com/redhat/devtools/intellij/common/actions/TreeAction.java

Call isVisible when processing multiple items isVisible

---

src/main/java/com/redhat/devtools/intellij/common/actions/TreeAction.java

Fix wrong fix for #31

---

build.gradle

Publish sources and javadocs to Nexus

---

src/main/java/com/redhat/devtools/intellij/common/tree/LabelAndIconDescriptor.java

Add supplier pattern to LabelAndIconDescriptor

---

src/main/java/com/redhat/devtools/intellij/common/utils/ExecHelper.java

this is used by https://github.com/redhat-developer/intellij-tekton/pull/318
In our case it allows to redirect logs to the editor when users specify it using settings

add method to execute process with UI

---

Jenkinsfile
build.gradle
gradle.properties

Prepare for 0.0.1

---

build.gradle

Update POM info for release publishing

---

build.gradle

fix: use kubernetes-client 5.0.2

---

gradle.properties

Prepare for 0.0.2

---

build.gradle
src/main/java/com/redhat/devtools/intellij/common/utils/YAMLHelper.java
src/main/java/com/redhat/devtools/intellij/common/validation/KubernetesTypeInfo.java
src/main/java/com/redhat/devtools/intellij/common/validation/SchemaProvider.java
src/main/java/com/redhat/devtools/intellij/common/validation/SchemasProviderFactory.java

This patch adds functions for schema validation and to work with YAML files that are in common in Tekton and Knative plugins

add schemas validation and extend YAML class

---

src/main/java/com/redhat/devtools/intellij/common/editor/AllowNonProjectEditing.java
src/main/java/com/redhat/devtools/intellij/common/editor/SaveInEditorListener.java

fixes #51 
related to https://github.com/redhat-developer/intellij-tekton/issues/391

feat: provide extension that prevents 'non-project file protection' dialog (#51)

---

src/main/java/com/redhat/devtools/intellij/common/tree/StructureTreeModelFactory.java
src/main/java/com/redhat/devtools/intellij/common/utils/ConfigHelper.java
src/main/java/com/redhat/devtools/intellij/common/utils/DownloadHelper.java
src/main/java/com/redhat/devtools/intellij/common/utils/HighSensitivityRegistrar.java

fix: corrected javadoc warnings (#53)

---

.github/workflows/conventionalCheck.yml
.github/workflows/release.yml

chore: Use conventional commits and add release workflow

---

.github/workflows/IJ.yml
src/main/java/com/redhat/devtools/intellij/common/utils/ExecHelper.java

chore: Add 2021.1

---

src/main/java/com/redhat/devtools/intellij/common/utils/ConfigHelper.java
src/test/java/com/redhat/devtools/intellij/common/utils/ConfigHelperTest.java

fix: retrieve token in AuthInfo#getToken (was: only auth providers)(#58)

---

gradle.properties

chore: Prepare for 1.0.0

---

.github/workflows/IJ.yml
.github/workflows/ci.yml

chore: Switch branch to main

---

src/main/java/com/redhat/devtools/intellij/common/utils/YAMLHelper.java
src/test/java/com/redhat/devtools/intellij/common/utils/YAMLHelperTest.java
src/test/resources/utils/YAMLHelper/invalid_service.yaml
src/test/resources/utils/YAMLHelper/missingmetadata_service.yaml
src/test/resources/utils/YAMLHelper/service.yaml
src/test/resources/utils/YAMLHelper/service_with_label.yaml
src/test/resources/utils/YAMLHelper/service_with_multiple_labels.yaml

this is related to https://github.com/redhat-developer/intellij-knative/pull/69

feat: add functions to add/remove label by having simple yaml

---

build.gradle
gradle.properties
src/main/java/com/redhat/devtools/intellij/common/tree/LabelAndIconDescriptor.java
src/main/java/com/redhat/devtools/intellij/common/tree/LinkElement.java
src/main/java/com/redhat/devtools/intellij/common/tree/TreeHelper.java
src/test/java/com/redhat/devtools/intellij/common/tree/LabelAndIconDescriptorTest.java

feat: Add support for links in tree

---

src/main/java/com/redhat/devtools/intellij/common/model/GenericResource.java
src/main/java/com/redhat/devtools/intellij/common/model/GenericResourceDeserializer.java
src/main/java/com/redhat/devtools/intellij/common/utils/StringHelper.java
src/test/java/com/redhat/devtools/intellij/common/utils/model/GenericResourceDeserializerTest.java
src/test/resources/model/resource.yaml
src/test/resources/model/resource_with_null_apiversion.yaml
src/test/resources/model/resource_with_null_kind.yaml
src/test/resources/model/resource_with_null_metadata.yaml
src/test/resources/model/resource_with_null_name.yaml
src/test/resources/model/resource_with_null_spec.yaml
src/test/resources/model/resource_without_apiversion.yaml
src/test/resources/model/resource_without_kind.yaml
src/test/resources/model/resource_without_metadata.yaml
src/test/resources/model/resource_without_name.yaml
src/test/resources/model/resource_without_spec.yaml

This is linked to https://github.com/redhat-developer/intellij-tekton/pull/405

feat: add generic resource model

---

src/main/java/com/redhat/devtools/intellij/common/utils/ExecHelper.java

fix: Correct invalid Javadoc statements

---

src/main/java/com/redhat/devtools/intellij/common/actions/TreeAction.java

feat: give extenders the chance to enable/disable an action

---

build.gradle
src/main/java/com/redhat/devtools/intellij/common/kubernetes/ClusterHelper.java
src/main/java/com/redhat/devtools/intellij/common/kubernetes/ClusterInfo.java
src/test/java/com/redhat/devtools/intellij/common/kubernetes/ClusterHelperTest.java

feat: Return basic cluster information

---

src/main/java/com/redhat/devtools/intellij/common/utils/YAMLHelper.java
src/test/java/com/redhat/devtools/intellij/common/utils/YAMLHelperTest.java

This allows to retrieve a value with a specific index from an array in YAML

feat: retrieve value from array in YAML

---

src/main/java/com/redhat/devtools/intellij/common/kubernetes/ClusterHelper.java

fix: Report correctly Kubernetes version for OpenShift clusters

---

gradle.properties

chore: Prepare for 1.2.0

---

gradle.properties
src/main/java/com/redhat/devtools/intellij/common/kubernetes/ClusterHelper.java

fix: ClusterHelper is NPE is the client is OpenShiftClient

---

gradle.properties

chore: Prepare for 1.2.1

---

gradle.properties

chore: Prepare for 1.2.2

---

.github/workflows/IJ.yml

build: add IntelliJ 2021.2

---

gradle.properties
src/main/java/com/redhat/devtools/intellij/common/utils/UIHelper.java

feat: Add new method to detect if current theme/LAF is dark or not

---

src/main/java/com/redhat/devtools/intellij/common/kubernetes/ClusterHelper.java

fix: close DefaultKubernetesClient once it's not used any more (#102)

---

.github/workflows/IJ.yml
gradle.properties
src/main/java/com/redhat/devtools/intellij/common/listener/TreeDoubleClickListener.java
src/main/java/com/redhat/devtools/intellij/common/notification/NotificationGroupFactory.java
src/main/java/com/redhat/devtools/intellij/common/tree/MutableModelSynchronizer.java
src/main/java/com/redhat/devtools/intellij/common/utils/ExecHelper.java

refactor: require IC-2019.3 and replace API usage scheduled for removal (excluding terminal)

---

src/main/java/com/redhat/devtools/intellij/common/utils/UIHelper.java

fix: NPE thrown by isDark method in unit tests

---

build.gradle
src/main/java/com/redhat/devtools/intellij/common/compat/NotificationGroupFactory.java
src/main/java/com/redhat/devtools/intellij/common/compat/PopupHandlerAdapter.java

fix: allow PopupHandler#installPopupHandler in IC-2021.3 (#93)

---

src/main/java/com/redhat/devtools/intellij/common/utils/ExecHelper.java
src/main/java/com/redhat/devtools/intellij/common/utils/ExecProcessHandler.java
src/main/java/com/redhat/devtools/intellij/common/utils/ExecReader.java
src/main/java/com/redhat/devtools/intellij/common/utils/ExecRunContentDescriptor.java

So, this is the final solution for me.
https://github.com/redhat-developer/intellij-common/pull/91 has this issue  https://github.com/redhat-developer/intellij-common/pull/91#issuecomment-926700233
https://github.com/redhat-developer/intellij-common/pull/99 is too hacky, i needed to override many classes and i'm afraid it can be a problem in future releases. If they change something we need to edit it again.
This PR is the one that requires less changes even in the other plugins (method signature remains the same) and the TerminalExecutionConsole will be kept as it is for the moment. No breaking changes in the near future :crossed_fingers: 
The overall behavior/experience will remain the same as it is today so users wouldn't see much differences.
It allows user interactions.
I tried it …

feat: update executeInterminal with TerminalExecutionConsole

---

gradle.properties

chore: bump to version 1.4.0 (#112)

---

src/main/java/com/redhat/devtools/intellij/common/tree/MutableModelSynchronizer.java

fix: add NPE guard when invalidate path

---

.github/workflows/IJ.yml
build.gradle

build: Add IntelliJ 2021.3

---

src/test/java/com/redhat/devtools/intellij/common/utils/VfsRootAccessHelper.java

feat: add VfsRootAccesshelper for IntelliJ 2021.3 compatibility

---

src/test/java/com/redhat/devtools/intellij/common/utils/VfsRootAccessHelper.java

fix: VfsRootAccessHelper broken on IntelliJ < 2021.3

---

src/main/java/com/redhat/devtools/intellij/common/validation/KubernetesResourceInfo.java

feat: KubernetesResourceInfo to retrieve name & namespace via PSI (#126)

---

.github/workflows/release.yml
gradle.properties

chore(skip-release): Prepare for 1.5.0

---

.github/workflows/IJ.yml
build.gradle
src/test/java/com/redhat/devtools/intellij/common/FixtureBaseTest.java

build: Add IntelliJ 2022.1

---

gradle.properties

chore(skip-release): Prepare for 1.6.0

---

src/main/java/com/redhat/devtools/intellij/common/model/ProcessHandlerInput.java
src/main/java/com/redhat/devtools/intellij/common/utils/ExecHelper.java

This is used by https://github.com/redhat-developer/intellij-knative/pull/176 so we can create and handle a process externally (to stop it for example)

feat: allow to create process handler externally

---

.github/workflows/IJ.yml
build.gradle
gradle.properties

chore: bumped to kubernetes-client 5.12.2 & min IC-2021.1 (#132)

---

gradle.properties

chore(skip-release): Bump to 1.8.0-SNAPSHOT

---

src/main/java/com/redhat/devtools/intellij/common/utils/YAMLHelper.java

chore: removed duplicate code in YAMLHelper (#150)

---

src/main/java/com/redhat/devtools/intellij/common/utils/CommonTerminalExecutionConsole.java
src/main/java/com/redhat/devtools/intellij/common/utils/ExecHelper.java
src/main/java/com/redhat/devtools/intellij/common/utils/VirtualFileHelper.java

feat: add ProcessListener support when running in non terminal mode

---

src/main/java/com/redhat/devtools/intellij/common/ui/InputDialogWithCheckbox.java

this is used by https://github.com/redhat-developer/intellij-knative/pull/212

feat: add InputDialogWithCheckbox with customizable behavior

---

build.gradle

chore: bumped openshift-client to 5.12.4 (#166)

---

gradle.properties

chore(skip-release): Prepare for 1.8.0

---

gradle.properties

chore(skip-release): bump to 1.9.0-SNAPSHOT

---

build.gradle
src/main/java/com/redhat/devtools/intellij/common/utils/MetadataClutter.java
src/test/java/com/redhat/devtools/intellij/common/utils/MetadataClutterTest.java

feat: bump kubernetes-client to 6.4.0 (#172)

---

src/main/java/com/redhat/devtools/intellij/common/kubernetes/ClusterHelper.java
src/test/java/com/redhat/devtools/intellij/common/kubernetes/ClusterHelperTest.java

Signed-off-by: Stephane Bouchet <sbouchet@redhat.com>

fix: avoid try-with-resources when using clients

---

.github/workflows/IJ.yml

chore: added verification of IC-2022.3 (#171)

---

src/main/java/com/redhat/devtools/intellij/common/utils/IDEAContentFactory.java

chore: added means to get ContentFactory pre-/post-IC-2023.1 (#181)

---

build.gradle

chore: added twelvemonkeys/common-lang to provide Platform rm'd in IC-2023.1 (#178)

---

src/main/java/com/redhat/devtools/intellij/common/tree/MutableModelSynchronizer.java

This is needed by https://github.com/redhat-developer/intellij-openshift-connector/issues/524 where nodes notify changes in background threads.
There are 2 things changed here: 
* `onModified` should update descriptor that's modifed (was: only invalidate children)
* `onModifed`, `onAdded`, `onRemoved` should invalidate using the invoker thread, not the current thread.

fix: update modified descriptor, use correct thread when processing change

---

src/main/java/com/redhat/devtools/intellij/common/utils/DownloadHelper.java
src/main/java/com/redhat/devtools/intellij/common/utils/UIHelper.java
src/main/java/com/redhat/devtools/intellij/common/validation/SchemasProviderFactory.java

fix: correct incompatibilities to IC-2024.1 (#207)

---

src/main/java/com/redhat/devtools/intellij/common/kubernetes/ClusterHelper.java
src/test/java/com/redhat/devtools/intellij/common/kubernetes/ClusterHelperTest.java

fixes #216 
matches the implementation in jkube: 
https://github.com/eclipse/jkube/blob/2ebeabe2ae6ebbcd52e0fd9323607892bcb831d4/jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/OpenshiftHelper.java#L51

fix: corrected check for OpenShift cluster (#216)

---

build.gradle

refactor: bump kubernetes-client to 6.12.0 (#210)

---

gradle.properties

chore(skip-release): Prepare for 1.9.4

---

.gitignore
build.gradle
src/main/java/com/redhat/devtools/intellij/common/CommonConstants.java
src/main/java/com/redhat/devtools/intellij/common/utils/DownloadHelper.java
src/test/java/com/redhat/devtools/intellij/common/utils/DownloadHelperTest.java
src/test/java/com/redhat/devtools/intellij/common/utils/ToolsConfigTest.java
src/test/resources/tkn-override-basedir-test.json
src/test/resources/tkn-test-invalid-checksum.json

feat: add system property to override download path

---

.github/workflows/IJ-latest.yml

chore(skip-release): fix IJ-latest.yml

---

build.gradle.kts

fix: corrected component to be published, removed hacks (#251)

---

Jenkinsfile
settings.gradle
settings.gradle.kts

chore: moved jenkins build to new server

---

src/main/java/com/redhat/devtools/intellij/common/utils/ConfigWatcher.java
src/test/java/com/redhat/devtools/intellij/common/utils/ConfigWatcherTest.java

feat: inform ConfigWatcher event consumers of errors when parsing the config(s) (#259)

---

src/main/java/com/redhat/devtools/intellij/common/utils/KubeconfigEnvValue.java

fix: copy env vars to java System to have KUBECONFIG available (#263)

---

gradle.properties

chore(skip-release): prepare 1.9.8 (#265)

---

build.gradle.kts
gradle.properties
gradle/libs.versions.toml

chore: fix latest IJ / IC-2025.1 EAP

---

src/main/java/com/redhat/devtools/intellij/common/validation/KubernetesResourceInfo.java
src/main/java/com/redhat/devtools/intellij/common/validation/KubernetesTypeInfo.java
src/main/java/com/redhat/devtools/intellij/common/validation/SchemaProvider.java
src/test/java/com/redhat/devtools/intellij/common/validation/KubernetesResourceInfoTest.java
src/test/java/com/redhat/devtools/intellij/common/validation/KubernetesTypeInfoTest.java

* added support for multi-resource yaml files
* added tests for `KubernetesTypeInfo`

fix: support multi-resource yaml files

---

.github/dependabot.yml
.github/workflows/dependency-submission.yml

chore: add dependabot workflow

---

gradle.properties
gradle/libs.versions.toml

fix: Revert jackson 2.19
