redhat-developer/intellij-common

src/main/java/com/redhat/devtools/intellij/common/CommonConstants.java
src/main/java/com/redhat/devtools/intellij/common/actions/StructureTreeAction.java
src/main/java/com/redhat/devtools/intellij/common/actions/TreeAction.java

This is linked with https://github.com/redhat-developer/intellij-tekton/issues/83
This patch adds support for multiple selection in a tree and make actions appear/work when multiple items are selected.
Until now if you selected multiple items only the first one was taken as arg for an action.
To change the behavior, first you need to setup a property `TREE_MULTIPLE_SELECTION` to true in the tree and then add a property `acceptMultipleItems` for each action you want to handle multiple items. This way the context menu will show only the possible actions.
If nothing is set up it works exactly as before so the other extensions that use this library can also maintain their current code.
An example below.
This is when only one item is selected, the context menu contains everything as before. …

added support for actions on multiple selection in tree

---

build.gradle
src/main/java/com/redhat/devtools/intellij/common/utils/ConfigHelper.java
src/test/java/com/redhat/devtools/intellij/common/utils/ConfigHelperTest.java

is a dependency for https://github.com/redhat-developer/intellij-kubernetes/issues/154
fixes #27 
Allows to compare (kubeconfig) file config and (runtime) client config to figure out if changes happened.

Also compare tokens when checking (file- & client-)configs for changes

---

src/main/java/com/redhat/devtools/intellij/common/utils/DownloadHelper.java
src/test/java/com/redhat/devtools/intellij/common/utils/DownloadHelperTest.java
src/test/resources/knative-test.json

When `dlFileName` and `cmdFileName` are the same, without this fix we open input and output stream on same file which lead to breaking file content. 
It is a blocker for https://github.com/redhat-developer/intellij-knative/issues/1 as `kn` CLI released as plain binnary.

Do not uncompress downloaded file if it not an archive

---

src/main/java/com/redhat/devtools/intellij/common/actions/TreeAction.java

When Action placed not only on context menu for tree, it is possible to get `ClassCastException` on `getTree` method.
This PR add check and return `null` if `CONTEXT_COMPONENT` contains not `Tree` component.
Need for https://github.com/redhat-developer/intellij-knative/pull/18

Fix ClassCastException on getTree method

---

src/main/java/com/redhat/devtools/intellij/common/CommonConstants.java
src/main/java/com/redhat/devtools/intellij/common/listener/SaveInEditorListener.java
src/main/java/com/redhat/devtools/intellij/common/listener/TreeDoubleClickListener.java
src/main/java/com/redhat/devtools/intellij/common/listener/TreePopupMenuListener.java
src/main/java/com/redhat/devtools/intellij/common/utils/DeployModel.java
src/main/java/com/redhat/devtools/intellij/common/utils/VirtualFileHelper.java

This patch adds tools to work with files and tree (save file from the editor, double click on the tree, tree menu popup ...) used in tekton and knative plugins

Listeners + helpers in common between Tekton/Knative

---

src/main/java/com/redhat/devtools/intellij/common/actions/TreeAction.java

this resolves an issue we have in knative https://github.com/redhat-developer/intellij-knative/issues/35

prevent ArrayIndexOutOfBoundsException when using a toolbar action and no element is selected

---

src/main/java/com/redhat/devtools/intellij/common/actions/TreeAction.java

This PR do next:
- Disables action when we hide action
- Fix NPE when action called with keybinding
> If we decide to use more keybindings, we need to be careful with enable/disable action, currently we just hide action when we do not want to allowing action execution, it only remove action from UI,  but not disable action and it is still possible to execute it with keybinding.

Fix action perform and enable 

---

src/main/java/com/redhat/devtools/intellij/common/utils/ConfigWatcher.java

This fixes a possible issue you face due to some editor behavior (e.g gedit).
In some editor, when you edit the file, the editor creates a new temp file, edit it and then use it to recreate the original file so if you only listen to the edit/delete action nothing happens and the plugins are never refreshed.

add create kind to watchservice

---

src/main/java/com/redhat/devtools/intellij/common/utils/ExecHelper.java

During work on https://github.com/redhat-developer/intellij-knative/issues/38 I found that `kn` cli can print some errors/warnings for some kommand in `stderr` stream. Existing `execute` method combines `sdtout` and `stderr` streams in to one string which we trying to parse as JSON, which fails as string not contain valid JSON.
This PR just add new method `executeWithResult` which return object with `sdtout` and `stderr` placed separately.
I not 100% sure how to properly fix existing methods, as do not want to break other code, so I just deprecate `execute` methods. Other option can be change `execute`  to use two streams for `sdtout` and `stderr`. But I not sure what we need to do with `stderr` in such case.
It blocker for https://github.com/redhat-developer/intellij-knative/issues/38

Add new 'executeWithResult' method

---

src/main/java/com/redhat/devtools/intellij/common/utils/ExecHelper.java

The title says it all. By returing the scheduledFuture we are allowed to cancel a scheduled runnable somewhere else

feat: make executeAfter returns the scheduledFuture to being able to cancel it

---

src/main/java/com/redhat/devtools/intellij/common/utils/ConfigHelper.java
src/test/java/com/redhat/devtools/intellij/common/utils/ConfigHelperTest.java

Added a new method to just compare the current context of two configs. Current implementation also checks the list of all contexts available and it doesn't support two `io.fabric8.kubernetes.api.model.Config` which is what i have when watching the kubeconfig to know if the tree needs to be refreshed.

feat: Add config checker to compare current contexts of two configs

---

Jenkinsfile
build.gradle

fix: use gradle-nexus.publish-plugin to publish to Nexus

---

src/main/java/com/redhat/devtools/intellij/common/utils/DownloadHelper.java
src/main/java/com/redhat/devtools/intellij/common/utils/ToolsConfig.java
src/test/resources/tkn-test-gz.json
src/test/resources/tkn-test-tar.gz.json
src/test/resources/tkn-test.json

feat: add silentMode to DownloadHelper (#121)

---

src/main/java/com/redhat/devtools/intellij/common/utils/ExecProcessHandler.java

When not extending `KillableProcessHandler` the stop action (the 🟥 button) will SIGKILL to the console app.
When extending `KillableProcessHandler` it will send `SIGINT` or `SIGTERM` first giving opportunity to clean up.
resolves #135

fix: Graceful termination for terminal runs

---

src/main/java/com/redhat/devtools/intellij/common/utils/DownloadHelper.java

This is needed so that we can add different versions of a CLI for darwin in our configuration files. MAC M1 needs arm64 versions to work.
This is only made to correctly behaves with arm64/amd64. If it happens that someone uses s390x, ppc64le or some weird os arch  it still executes as before. Not sure if we need to handle everything.

feat: support different os architectures when downloading

---

src/main/java/com/redhat/devtools/intellij/common/utils/CommonTerminalExecutionConsole.java
src/main/java/com/redhat/devtools/intellij/common/utils/ExecHelper.java
src/main/java/com/redhat/devtools/intellij/common/utils/ExecRunContentDescriptor.java

This PR allows to execute multiple commands in the same terminal tab. 
It is needed by https://github.com/redhat-developer/intellij-knative/pull/128
I needed to write a custom TerminalExecutionConsole as in the existing one i could not extend/use AppendableTerminalDataStream and `printText(@NotNull String text, @Nullable ConsoleViewContentType contentType)` method. I'm all ears if you have a cleaner way to achieve it.
Example

feat: Allow to execute command in existing terminal tab

---

src/main/java/com/redhat/devtools/intellij/common/utils/ExecHelper.java

This is used by https://github.com/redhat-developer/intellij-knative/pull/162
1) Allow to attach a process listener so the process state can be checked externally
2) `CommonTerminalExecutionConsole` is replaced by ConsoleView so the method can also be called with the default `TerminalExecutionConsole`

feat: add process listener attach option so to listen to the process externally

---

src/main/java/com/redhat/devtools/intellij/common/utils/ExecHelper.java

fixes #148 
This is required by openshift connector -> https://github.com/redhat-developer/intellij-openshift-connector/pull/425
Is this the only one missing right?

fix: add back executeWithTerminal method signature deleted wrongly

---

gradle.properties

we need to release a new version of intellij-openshift-connector. See [chore: bumped openshift-client 5.12.2 & intellij-common 1.7.1](https://github.com/redhat-developer/intellij-openshift-connector/pull/425/files#)
This should be 1.7.1 though since none of the commits since 1.7.0 would break the API (a method was added: https://github.com/redhat-developer/intellij-common/issues/148)
@jeffmaury, @lstocchi: thoughts?

chore: release 1.7.1

---

src/main/java/com/redhat/devtools/intellij/common/CommonConstants.java
src/main/java/com/redhat/devtools/intellij/common/utils/ObjectMetadataClutter.java
src/main/java/com/redhat/devtools/intellij/common/utils/VirtualFileHelper.java
src/main/java/com/redhat/devtools/intellij/common/utils/YAMLHelper.java

moved the method for YAML clutter cleanup from `VirtualFileHelper` to it's own class. IMHO this is better when it comes to separation of concerns. I kept the original methods and marked them as deprecated for smoother migration of existing consumers.
This is to prepare the next step where I add support for JSON (it currently only supports YAML)

chore: extracted methods for YAML clutter removal from VirutalFileHelper

---

src/main/java/com/redhat/devtools/intellij/common/utils/ConfigHelper.java
src/test/java/com/redhat/devtools/intellij/common/utils/ConfigHelperTest.java

fix: don't NPE when kube config has no current context (#163)

---

.github/workflows/release.yml

The last release workflow failed because of this step. It already happened in other repos.
I'm removing it as this is not really necessary, it was there just to see the output and check if everything was working fine.

chore(skip-release): remove run step from release workflow for printing out changelog

---

.github/workflows/IJ.yml
build.gradle
src/test/java/com/redhat/devtools/intellij/common/FixtureBaseTest.java
src/test/java/com/redhat/devtools/intellij/common/actions/editor/RemoveYAMLClutterActionHandlerTest.java

chore: added IC-2023.2 to verified platforms (#193)

---

src/main/java/com/redhat/devtools/intellij/common/utils/ConfigHelper.java

without this fix, when a corrupt `tools.json` is loaded the user gets a cryptic jackson mapper error. 
With the fix:

fix: report that loading tools.json failed (was: jackson error)

---

src/main/java/com/redhat/devtools/intellij/common/utils/ConfigHelper.java
src/main/java/com/redhat/devtools/intellij/common/utils/ToolsConfig.java

`ToolsConfig` is annotated with `@JsonIgnoreProperties(ignoreUnknown = true)` but it's missing from `Tools` and jackson thus throws `UnrecognizedPropertyException` when a tool in `tools.json` contains unknown properties.
To reproduce add `description` property to `odo` in `tools.json` or simply copy `tools.json` over from vscode-openshift-tools (https://github.com/redhat-developer/vscode-openshift-tools/blob/main/src/tools.json#L3C9-L3C34):
```json
"tools": {
"odo": {
"description": "odo CLI",
```

fix: ignore unknown properties when unmarshalling ToolsConfig

---

src/main/java/com/redhat/devtools/intellij/common/utils/ConfigHelper.java
src/main/java/com/redhat/devtools/intellij/common/utils/ConfigWatcher.java
src/test/java/com/redhat/devtools/intellij/common/utils/ConfigHelperTest.java

fix: notify if config file was deleted, allow to compare fileconfig-contexts (#201)

---

build.gradle
gradle.properties
src/main/java/com/redhat/devtools/intellij/common/CommonConstants.java
src/main/java/com/redhat/devtools/intellij/common/ssl/IDEATrustManager.java
src/test/java/com/redhat/devtools/intellij/common/ssl/IDEATrustManagerTest.java

see https://github.com/redhat-developer/intellij-kubernetes/issues/718
fixes #200

chore: Move IDEATrustManager from Kubernetes to Common

---

.github/workflows/IJ.yml
.github/workflows/ci.yml
.github/workflows/release.yml
Jenkinsfile
gradle.properties
src/main/java/com/redhat/devtools/intellij/common/actions/StructureTreeAction.java

fix: default update thread for actions is EDT (#218)

---

src/main/java/com/redhat/devtools/intellij/common/utils/DownloadHelper.java
src/test/java/com/redhat/devtools/intellij/common/utils/DownloadHelperTest.java

feat: DownloadHelper#downloadIfRequired allows to know if was downloaded

---

src/main/java/com/redhat/devtools/intellij/common/utils/DownloadHelper.java
src/main/java/com/redhat/devtools/intellij/common/utils/ToolsConfig.java
src/test/java/com/redhat/devtools/intellij/common/utils/DownloadHelperTest.java
src/test/java/com/redhat/devtools/intellij/common/utils/ToolsConfigTest.java
src/test/resources/tkn-test-invalid-checksum.json

feat: check checksums when downloading tools from json

---

.github/workflows/ci.yml
gradle.properties

fixes #234 
for https://github.com/redhat-developer/intellij-kubernetes/pull/781 I'll update `ConfigWatcher`. Before this change I want to release intellij-common. Thus triggering this release.

chore(skip-release): prepare 1.9.6

---

.github/workflows/IJ-latest.yml

github artifact actions v2 [wont be usable](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/) any longer this November:
>Starting November 30, 2024, GitHub Actions customers will no longer be able to use v3 of [actions/upload-artifact](https://github.com/actions/upload-artifact) or [actions/download-artifact](https://github.com/actions/download-artifact).

fix: bump github artifact actions to v4

---

src/main/java/com/redhat/devtools/intellij/common/utils/ConfigWatcher.java
src/test/java/com/redhat/devtools/intellij/common/utils/ConfigWatcherTest.java

feat: allow ConfigWatcher to watch several files (#236)

---

src/main/java/com/redhat/devtools/intellij/common/utils/IdeProxyAdapter.java
src/main/java/com/redhat/devtools/intellij/common/utils/NetworkUtils.java

fixes #242, #255
depends on 
* #243   
* https://github.com/redhat-developer/intellij-openshift-connector/issues/889 (can only test this using intellij-openshift-connector who's a consumer of this API)

fix: replace HttpConfigurable with adapter to support pre/post-2024.3 (#242)

---

.github/workflows/IJ.yml
build.gradle.kts
gradle.properties
gradle/libs.versions.toml
src/main/java/com/redhat/devtools/intellij/common/kubernetes/ClusterHelper.java
src/main/java/com/redhat/devtools/intellij/common/utils/ConfigHelper.java
src/main/java/com/redhat/devtools/intellij/common/utils/ConfigWatcher.java
src/main/java/com/redhat/devtools/intellij/common/utils/DownloadHelper.java
src/main/java/com/redhat/devtools/intellij/common/utils/ToolsConfigHelper.java
src/test/java/com/redhat/devtools/intellij/common/kubernetes/ClusterHelperTest.java
src/test/java/com/redhat/devtools/intellij/common/utils/ConfigHelperTest.java
src/test/java/com/redhat/devtools/intellij/common/utils/ConfigWatcherTest.java
src/test/java/com/redhat/devtools/intellij/common/utils/ToolsConfigTest.java

fix: bump kubernetes- and openshift-client to 7.0.0 (#247)

---

src/main/java/com/redhat/devtools/intellij/common/validation/KubernetesResourceInfo.java
src/test/java/com/redhat/devtools/intellij/common/validation/KubernetesResourceInfoTest.java

required for https://github.com/redhat-developer/intellij-kubernetes/pull/853

fix: hide typeInfo in KubeResourceInfo but allow access to apiGroup, kind

---

.github/workflows/release.yml
README.md

build: migrate from jenkins to github maven repo / release version
